spring:
  application:
    name: Vigilia
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    cache-names:
      - embeddingSearch
    caffeine:
      spec: maximumSize=50,expireAfterAccess=600s
server:
  port: 54913
  address: 127.0.0.1
vigilia:
  data:
    appdir: ${user.home}${file.separator}.vigilia
    datasource.url: jdbc:sqlite:${vigilia.data.appdir}${file.separator}vigilia.db?enable_load_extension=true
  vector-store:
    initialize-schema: true
    schema-name: public
